spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: mallchat
  datasource:
    url: jdbc:mysql://${mallchat.mysql.ip}:${mallchat.mysql.port}/${mallchat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mallchat.mysql.username}
    password: ${mallchat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: true
  data:
    redis:
      #pas#sword: ${mallchat.redis.password}
      timeout: 1800000
      database: 0
      port: ${mallchat.redis.port}
      host: ${mallchat.redis.host}
wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${mallchat.wx.callback}
    configs:
      - appId: ${mallchat.wx.appId} # 第一个公众号的appid
        secret: ${mallchat.wx.secret} # 公众号的appsecret
        token: ${mallchat.wx.token} # 接口配置里的Token值
        aesKey: ${mallchat.wx.aesKey} # 接口配置里的EncodingAESKey值
jwt:
  secret: ${mallchat.jwt.secret}
springdoc:
  api-docs:
    #是否开启文档功能关系到swagger-ui能否开启
    enabled: true
    #swagger后端请求地址，查看swagger所有配置，同时也是配置web端的接口配置,必须写
    path: /v3/api-docs
  swagger-ui:
    #标签排序
    tags-sorter: alpha
    #操作排序
    operations-sorter: alpha
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger会自动重定向到swagger页面注意是path不是url
    path: /swagger
  group-configs:
    - group: 用户模块
      packages-to-scan:
        - com.shiyi.user.controller
  packages-to-scan:
    - com.shiyi
  # knife4j的增强配置，不需要增强可以不配
knife4j:
  #开启访问默认路径doc.html
  enable: true
  setting:
    language: zh_cn
    #不开启缓存请求
    enable-request-cache: false
  #跨域请求
  cors: true

