##################mysql##################
mallchat.mysql.ip=127.0.0.1
mallchat.mysql.port=3306
mallchat.mysql.db=mallchat
mallchat.mysql.username=root
mallchat.mysql.password=3401187804
##################redis##################
mallchat.redis.host=127.0.0.1
mallchat.redis.port=6379
#mallchat.redis.password=
##################wx##################
mallchat.wx.callback=http://jp.frp.one:40155
mallchat.wx.appId=wx0ec50969b90a2eae
mallchat.wx.secret=77cbe20900222e5ee0cfebf9af4c8874
# ??????Token?
mallchat.wx.token=adadad
##################jwt##################
mallchat.jwt.secret=dsfsdfsdfsdfsd
